from __future__ import annotations

from dataclasses import dataclass

from research_assistant.cli_registration.common import Handler, Subparsers


@dataclass(frozen=True, slots=True)
class IndustrialHandlers:
    artifact_paths: Handler
    industrial_validate: Handler
    domain_templates: Handler
    derivation: Handler
    experiment: Handler
    graph_report: Handler
    review_meta: Handler
    benchmark_manifest: Handler
    synthesis: Handler
    governance: Handler
    job: Handler
    dashboard_export: Handler
    traceability: Handler
    model_policy: Handler
    collaboration: Handler
    artifact_index: Handler
    industrial_readiness: Handler
    full_scale_plan: Handler
    industrial_release: Handler
    tool_contract: Handler
    operations_policy: Handler
    sop: Handler


def register_industrial_commands(sub: Subparsers, handlers: IndustrialHandlers) -> None:
    """Register future industrial-platform scaffold commands."""
    artifact_paths_cmd = sub.add_parser('artifact-paths')
    artifact_paths_cmd.set_defaults(func=handlers.artifact_paths)

    industrial_validate = sub.add_parser('industrial-validate')
    industrial_validate.set_defaults(func=handlers.industrial_validate)

    domain_templates = sub.add_parser('domain-templates')
    domain_templates_sub = domain_templates.add_subparsers(dest='template_action', required=True)
    domain_templates_list = domain_templates_sub.add_parser('list')
    domain_templates_list.set_defaults(func=handlers.domain_templates)
    domain_templates_show = domain_templates_sub.add_parser('show')
    domain_templates_show.add_argument('--template-id', required=True)
    domain_templates_show.set_defaults(func=handlers.domain_templates)

    derivation = sub.add_parser('derivation')
    derivation_sub = derivation.add_subparsers(dest='derivation_action', required=True)
    derivation_create = derivation_sub.add_parser('create')
    derivation_create.add_argument('--paper-id', required=True)
    derivation_create.add_argument('--title', required=True)
    derivation_create.add_argument('--template-id')
    derivation_create.set_defaults(func=handlers.derivation)
    derivation_show = derivation_sub.add_parser('show')
    derivation_show.add_argument('--artifact-id', required=True)
    derivation_show.set_defaults(func=handlers.derivation)
    derivation_append = derivation_sub.add_parser('append')
    derivation_append.add_argument('--artifact-id', required=True)
    derivation_append.add_argument('--field', required=True)
    derivation_append.add_argument('--value', required=True)
    derivation_append.set_defaults(func=handlers.derivation)
    derivation_notation = derivation_sub.add_parser('notation')
    derivation_notation.add_argument('--artifact-id', required=True)
    derivation_notation.add_argument('--symbol', required=True)
    derivation_notation.add_argument('--meaning', required=True)
    derivation_notation.set_defaults(func=handlers.derivation)
    derivation_link_steps = derivation_sub.add_parser('link-steps')
    derivation_link_steps.add_argument('--artifact-id', required=True)
    derivation_link_steps.add_argument('--step-id', required=True)
    derivation_link_steps.add_argument('--depends-on', required=True)
    derivation_link_steps.set_defaults(func=handlers.derivation)
    derivation_comment = derivation_sub.add_parser('comment')
    derivation_comment.add_argument('--artifact-id', required=True)
    derivation_comment.add_argument('--target-id', required=True)
    derivation_comment.add_argument('--comment', required=True)
    derivation_comment.add_argument('--reviewer')
    derivation_comment.set_defaults(func=handlers.derivation)

    experiment = sub.add_parser('experiment')
    experiment_sub = experiment.add_subparsers(dest='experiment_action', required=True)
    experiment_checklists = experiment_sub.add_parser('checklists')
    experiment_checklists.set_defaults(func=handlers.experiment)
    experiment_checklist_show = experiment_sub.add_parser('checklist-show')
    experiment_checklist_show.add_argument('--template-id', required=True)
    experiment_checklist_show.set_defaults(func=handlers.experiment)
    experiment_create = experiment_sub.add_parser('create')
    experiment_create.add_argument('--paper-id', required=True)
    experiment_create.add_argument('--claim-id', required=True)
    experiment_create.add_argument('--checklist-id', required=True)
    experiment_create.set_defaults(func=handlers.experiment)
    experiment_show = experiment_sub.add_parser('show')
    experiment_show.add_argument('--artifact-id', required=True)
    experiment_show.set_defaults(func=handlers.experiment)
    experiment_link = experiment_sub.add_parser('link-claim')
    experiment_link.add_argument('--paper-id', required=True)
    experiment_link.add_argument('--claim-id', required=True)
    experiment_link.add_argument('--experiment-id', required=True)
    experiment_link.set_defaults(func=handlers.experiment)
    experiment_run = experiment_sub.add_parser('record-run')
    experiment_run.add_argument('--artifact-id', required=True)
    experiment_run.add_argument('--run-label', required=True)
    experiment_run.add_argument('--seed', required=True)
    experiment_run.add_argument('--environment', required=True)
    experiment_run.add_argument('--diagnostic', action='append', default=[])
    experiment_run.add_argument('--result-summary')
    experiment_run.add_argument('--acceptance-status', default='requires_review')
    experiment_run.add_argument('--dataset-hash')
    experiment_run.add_argument('--model-hash')
    experiment_run.set_defaults(func=handlers.experiment)

    graph_report = sub.add_parser('graph-report')
    graph_report_sub = graph_report.add_subparsers(dest='graph_report_action', required=True)
    graph_report_build = graph_report_sub.add_parser('build')
    graph_report_build.add_argument('--paper-id', required=True)
    graph_report_build.set_defaults(func=handlers.graph_report)
    graph_report_show = graph_report_sub.add_parser('show')
    graph_report_show.add_argument('--artifact-id', required=True)
    graph_report_show.set_defaults(func=handlers.graph_report)
    graph_report_enrich = graph_report_sub.add_parser('enrich')
    graph_report_enrich.add_argument('--artifact-id', required=True)
    graph_report_enrich.set_defaults(func=handlers.graph_report)

    review_meta = sub.add_parser('review-meta')
    review_meta_sub = review_meta.add_subparsers(dest='review_meta_action', required=True)
    review_meta_show = review_meta_sub.add_parser('show')
    review_meta_show.add_argument('--paper-id', required=True)
    review_meta_show.set_defaults(func=handlers.review_meta)
    review_meta_set = review_meta_sub.add_parser('set')
    review_meta_set.add_argument('--paper-id', required=True)
    review_meta_set.add_argument('--field', required=True)
    review_meta_set.add_argument('--value', required=True)
    review_meta_set.set_defaults(func=handlers.review_meta)
    review_meta_list = review_meta_sub.add_parser('list')
    review_meta_list.set_defaults(func=handlers.review_meta)

    benchmark_manifest = sub.add_parser('benchmark-manifest')
    benchmark_sub = benchmark_manifest.add_subparsers(dest='benchmark_action', required=True)
    benchmark_create = benchmark_sub.add_parser('create')
    benchmark_create.add_argument('--manifest-id', required=True)
    benchmark_create.add_argument('--family', required=True)
    benchmark_create.add_argument('--fixture', action='append', default=[])
    benchmark_create.set_defaults(func=handlers.benchmark_manifest)
    benchmark_show = benchmark_sub.add_parser('show')
    benchmark_show.add_argument('--manifest-id', required=True)
    benchmark_show.set_defaults(func=handlers.benchmark_manifest)
    benchmark_run = benchmark_sub.add_parser('run')
    benchmark_run.add_argument('--manifest-id', required=True)
    benchmark_run.set_defaults(func=handlers.benchmark_manifest)

    synthesis = sub.add_parser('synthesis')
    synthesis_sub = synthesis.add_subparsers(dest='synthesis_action', required=True)
    synthesis_propose = synthesis_sub.add_parser('propose')
    synthesis_propose.add_argument('--paper-id', required=True)
    synthesis_propose.add_argument('--kind', required=True)
    synthesis_propose.set_defaults(func=handlers.synthesis)
    synthesis_show = synthesis_sub.add_parser('show')
    synthesis_show.add_argument('--artifact-id', required=True)
    synthesis_show.set_defaults(func=handlers.synthesis)

    governance = sub.add_parser('governance')
    governance_sub = governance.add_subparsers(dest='governance_action', required=True)
    governance_build = governance_sub.add_parser('build')
    governance_build.add_argument('--paper-id', required=True)
    governance_build.set_defaults(func=handlers.governance)
    governance_show = governance_sub.add_parser('show')
    governance_show.add_argument('--artifact-id', required=True)
    governance_show.set_defaults(func=handlers.governance)

    job = sub.add_parser('job')
    job_sub = job.add_subparsers(dest='job_action', required=True)
    job_create = job_sub.add_parser('create')
    job_create.add_argument('--job-type', required=True)
    job_create.add_argument('--paper-id')
    job_create.set_defaults(func=handlers.job)
    job_show = job_sub.add_parser('show')
    job_show.add_argument('--artifact-id', required=True)
    job_show.set_defaults(func=handlers.job)

    dashboard_export_cmd = sub.add_parser('dashboard-export')
    dashboard_export_cmd.add_argument('--output')
    dashboard_export_cmd.set_defaults(func=handlers.dashboard_export)

    traceability = sub.add_parser('traceability')
    traceability_sub = traceability.add_subparsers(dest='traceability_action', required=True)
    traceability_build = traceability_sub.add_parser('build')
    traceability_build.add_argument('--paper-id', required=True)
    traceability_build.set_defaults(func=handlers.traceability)
    traceability_show = traceability_sub.add_parser('show')
    traceability_show.add_argument('--artifact-id', required=True)
    traceability_show.set_defaults(func=handlers.traceability)

    model_policy = sub.add_parser('model-policy')
    model_policy_sub = model_policy.add_subparsers(dest='model_policy_action', required=True)
    model_policy_create = model_policy_sub.add_parser('create')
    model_policy_create.add_argument('--policy-id', required=True)
    model_policy_create.set_defaults(func=handlers.model_policy)
    model_policy_show = model_policy_sub.add_parser('show')
    model_policy_show.add_argument('--policy-id', required=True)
    model_policy_show.set_defaults(func=handlers.model_policy)
    model_policy_check = model_policy_sub.add_parser('check-synthesis')
    model_policy_check.add_argument('--policy-id', required=True)
    model_policy_check.set_defaults(func=handlers.model_policy)

    collaboration = sub.add_parser('collaboration')
    collaboration_sub = collaboration.add_subparsers(dest='collaboration_action', required=True)
    collaboration_create = collaboration_sub.add_parser('create')
    collaboration_create.add_argument('--workspace-id', required=True)
    collaboration_create.set_defaults(func=handlers.collaboration)
    collaboration_show = collaboration_sub.add_parser('show')
    collaboration_show.add_argument('--workspace-id', required=True)
    collaboration_show.set_defaults(func=handlers.collaboration)
    collaboration_update = collaboration_sub.add_parser('update')
    collaboration_update.add_argument('--workspace-id', required=True)
    collaboration_update.add_argument('--action', required=True)
    collaboration_update.add_argument('--value', required=True)
    collaboration_update.add_argument('--target')
    collaboration_update.set_defaults(func=handlers.collaboration)

    artifact_index = sub.add_parser('artifact-index')
    artifact_index_sub = artifact_index.add_subparsers(dest='artifact_index_action', required=True)
    artifact_index_build = artifact_index_sub.add_parser('build')
    artifact_index_build.add_argument('--index-id', default='local_artifact_index')
    artifact_index_build.set_defaults(func=handlers.artifact_index)
    artifact_index_show = artifact_index_sub.add_parser('show')
    artifact_index_show.add_argument('--index-id', required=True)
    artifact_index_show.set_defaults(func=handlers.artifact_index)
    artifact_index_query = artifact_index_sub.add_parser('query')
    artifact_index_query.add_argument('--index-id', default='local_artifact_index')
    artifact_index_query.add_argument('--family')
    artifact_index_query.add_argument('--paper-id')
    artifact_index_query.set_defaults(func=handlers.artifact_index)

    industrial_readiness = sub.add_parser('industrial-readiness')
    readiness_sub = industrial_readiness.add_subparsers(dest='readiness_action', required=True)
    readiness_build = readiness_sub.add_parser('build')
    readiness_build.add_argument('--report-id', default='industrial_readiness')
    readiness_build.set_defaults(func=handlers.industrial_readiness)
    readiness_show = readiness_sub.add_parser('show')
    readiness_show.add_argument('--report-id', required=True)
    readiness_show.set_defaults(func=handlers.industrial_readiness)

    full_scale_plan = sub.add_parser('full-scale-plan')
    full_scale_sub = full_scale_plan.add_subparsers(dest='full_scale_action', required=True)
    full_scale_phases = full_scale_sub.add_parser('phases')
    full_scale_phases.set_defaults(func=handlers.full_scale_plan)
    full_scale_phase_show = full_scale_sub.add_parser('phase-show')
    full_scale_phase_show.add_argument('--phase-id', required=True)
    full_scale_phase_show.set_defaults(func=handlers.full_scale_plan)
    full_scale_registry_build = full_scale_sub.add_parser('registry-build')
    full_scale_registry_build.set_defaults(func=handlers.full_scale_plan)
    full_scale_registry_show = full_scale_sub.add_parser('registry-show')
    full_scale_registry_show.set_defaults(func=handlers.full_scale_plan)
    full_scale_usefulness = full_scale_sub.add_parser('usefulness-build')
    full_scale_usefulness.set_defaults(func=handlers.full_scale_plan)
    full_scale_readiness = full_scale_sub.add_parser('readiness-build')
    full_scale_readiness.set_defaults(func=handlers.full_scale_plan)

    industrial_release = sub.add_parser('industrial-release')
    industrial_release_sub = industrial_release.add_subparsers(dest='industrial_release_action', required=True)
    industrial_release_phases = industrial_release_sub.add_parser('phases')
    industrial_release_phases.set_defaults(func=handlers.industrial_release)
    industrial_release_phase_show = industrial_release_sub.add_parser('phase-show')
    industrial_release_phase_show.add_argument('--phase-id', required=True)
    industrial_release_phase_show.set_defaults(func=handlers.industrial_release)
    industrial_release_definition_build = industrial_release_sub.add_parser('definition-build')
    industrial_release_definition_build.set_defaults(func=handlers.industrial_release)
    industrial_release_definition_show = industrial_release_sub.add_parser('definition-show')
    industrial_release_definition_show.set_defaults(func=handlers.industrial_release)
    industrial_release_external = industrial_release_sub.add_parser('external-validation-build')
    industrial_release_external.add_argument('--validation-dir')
    industrial_release_external.set_defaults(func=handlers.industrial_release)
    industrial_release_publication = industrial_release_sub.add_parser('publication-check')
    industrial_release_publication.set_defaults(func=handlers.industrial_release)
    industrial_release_gate = industrial_release_sub.add_parser('gate-build')
    industrial_release_gate.set_defaults(func=handlers.industrial_release)
    industrial_release_show = industrial_release_sub.add_parser('show')
    industrial_release_show.add_argument('--artifact-id', required=True)
    industrial_release_show.set_defaults(func=handlers.industrial_release)

    tool_contract = sub.add_parser('tool-contract')
    tool_contract_sub = tool_contract.add_subparsers(dest='tool_contract_action', required=True)
    tool_contract_export = tool_contract_sub.add_parser('export')
    tool_contract_export.add_argument('--contract-id', default='local_tool_contract')
    tool_contract_export.set_defaults(func=handlers.tool_contract)
    tool_contract_show = tool_contract_sub.add_parser('show')
    tool_contract_show.add_argument('--contract-id', required=True)
    tool_contract_show.set_defaults(func=handlers.tool_contract)

    operations_policy = sub.add_parser('operations-policy')
    operations_sub = operations_policy.add_subparsers(dest='operations_action', required=True)
    operations_create = operations_sub.add_parser('create')
    operations_create.add_argument('--policy-id', default='department_operations_policy')
    operations_create.set_defaults(func=handlers.operations_policy)
    operations_show = operations_sub.add_parser('show')
    operations_show.add_argument('--policy-id', required=True)
    operations_show.set_defaults(func=handlers.operations_policy)

    sop = sub.add_parser('sop')
    sop_sub = sop.add_subparsers(dest='sop_action', required=True)
    sop_create = sop_sub.add_parser('create')
    sop_create.add_argument('--sop-id', default='department_research_sop')
    sop_create.set_defaults(func=handlers.sop)
    sop_show = sop_sub.add_parser('show')
    sop_show.add_argument('--sop-id', required=True)
    sop_show.set_defaults(func=handlers.sop)
