from __future__ import annotations

from research_assistant.cli_registration.common import Handler, Subparsers


def register_surveybench_commands(sub: Subparsers, handler: Handler) -> None:
    """Register offline and replay SurveyBench commands."""
    surveybench = sub.add_parser('surveybench', help='Run offline synthetic and online-replay SurveyBench fixtures')
    surveybench_sub = surveybench.add_subparsers(dest='surveybench_action', required=True)
    surveybench_run = surveybench_sub.add_parser('run', help='Run an offline SurveyBench task and emit JSON')
    surveybench_run.add_argument('--task', required=True)
    surveybench_run.add_argument('--actual-dir')
    surveybench_run.add_argument('--output')
    surveybench_run.set_defaults(func=handler)
    surveybench_manifest = surveybench_sub.add_parser('local-manifest', help='Validate a redacted local SurveyBench manifest')
    surveybench_manifest.add_argument('--manifest', required=True)
    surveybench_manifest.add_argument('--output')
    surveybench_manifest.set_defaults(func=handler)
    surveybench_replay_call = surveybench_sub.add_parser('replay-call', help='Call an offline online-replay endpoint and append a budgeted event log')
    surveybench_replay_call.add_argument('--task', required=True)
    surveybench_replay_call.add_argument('--endpoint', required=True)
    surveybench_replay_call.add_argument('--session', required=True)
    surveybench_replay_call.add_argument('--request-id')
    surveybench_replay_call.set_defaults(func=handler)
    surveybench_replay_audit = surveybench_sub.add_parser('replay-audit', help='Audit an online-replay fixture for interface and leakage issues')
    surveybench_replay_audit.add_argument('--task', required=True)
    surveybench_replay_audit.add_argument('--output')
    surveybench_replay_audit.set_defaults(func=handler)
    surveybench_replay_transcript = surveybench_sub.add_parser('replay-transcript', help='Build an offline replay transcript from a trusted session event log')
    surveybench_replay_transcript.add_argument('--task', required=True)
    surveybench_replay_transcript.add_argument('--session', required=True)
    surveybench_replay_transcript.add_argument('--output')
    surveybench_replay_transcript.set_defaults(func=handler)
    surveybench_replay_score = surveybench_sub.add_parser('replay-score', help='Score an online-replay submission packet against hidden fixture gold and an event log')
    surveybench_replay_score.add_argument('--task', required=True)
    surveybench_replay_score.add_argument('--actual-dir', required=True)
    surveybench_replay_score.add_argument('--event-log', required=True)
    surveybench_replay_score.add_argument('--gold-dir', required=True)
    surveybench_replay_score.add_argument('--output')
    surveybench_replay_score.set_defaults(func=handler)
    surveybench_score_prose = surveybench_sub.add_parser('score-prose', help='Score survey prose annotations after replay evidence-packet hard gates')
    surveybench_score_prose.add_argument('--task', required=True)
    surveybench_score_prose.add_argument('--actual-dir', required=True)
    surveybench_score_prose.add_argument('--event-log', required=True)
    surveybench_score_prose.add_argument('--gold-dir', required=True)
    surveybench_score_prose.add_argument('--prose', required=True)
    surveybench_score_prose.add_argument('--output')
    surveybench_score_prose.set_defaults(func=handler)
    surveybench_restricted_workspace = surveybench_sub.add_parser('restricted-workspace', help='Create a restricted SurveyBench replay-call workspace')
    surveybench_restricted_workspace.add_argument('--repo-root', default='.')
    surveybench_restricted_workspace.add_argument('--workspace', required=True)
    surveybench_restricted_workspace.add_argument('--profile', default='default')
    surveybench_restricted_workspace.add_argument('--output')
    surveybench_restricted_workspace.add_argument('--force', action='store_true')
    surveybench_restricted_workspace.set_defaults(func=handler)
    surveybench_restricted_launcher = surveybench_sub.add_parser('restricted-launcher-dry-run', help='Create a restricted SurveyBench launcher dry-run record without launching a subject')
    surveybench_restricted_launcher.add_argument('--workspace', required=True)
    surveybench_restricted_launcher.add_argument('--profile', default='default')
    surveybench_restricted_launcher.add_argument('--subject-agent', default='<unlaunched-subject-agent>')
    surveybench_restricted_launcher.add_argument('--output')
    surveybench_restricted_launcher.set_defaults(func=handler)
    surveybench_subject_binding = surveybench_sub.add_parser('subject-binding-preflight', help='Build a no-launch Claude subject permission binding preflight')
    surveybench_subject_binding.add_argument('--workspace', required=True)
    surveybench_subject_binding.add_argument('--profile', default='default')
    surveybench_subject_binding.add_argument('--subject-agent', default='claude-code-sonnet-subject')
    surveybench_subject_binding.add_argument('--model-id', default='claude-sonnet-4-6')
    surveybench_subject_binding.add_argument('--permission-mode', default='dontAsk')
    surveybench_subject_binding.add_argument('--subject-transport', default='claude-code')
    surveybench_subject_binding.add_argument('--representative-endpoint', default='search')
    surveybench_subject_binding.add_argument('--output')
    surveybench_subject_binding.set_defaults(func=handler)
    surveybench_launch_approval = surveybench_sub.add_parser('launch-approval-packet', help='Build and preflight a real-subject approval packet without launching')
    surveybench_launch_approval.add_argument('--launcher-dry-run', required=True)
    surveybench_launch_approval.add_argument('--subject-agent', required=True)
    surveybench_launch_approval.add_argument('--model-id', required=True)
    surveybench_launch_approval.add_argument('--subject-transport')
    surveybench_launch_approval.add_argument('--wrapper-command', nargs='+')
    surveybench_launch_approval.add_argument('--wrapper-command-json')
    surveybench_launch_approval.add_argument('--subject-binding-preflight')
    surveybench_launch_approval.add_argument('--budget-cap-json', required=True)
    surveybench_launch_approval.add_argument('--transcript-path', required=True)
    surveybench_launch_approval.add_argument('--denied-tool-capture-path', required=True)
    surveybench_launch_approval.add_argument('--cli-version', required=True)
    surveybench_launch_approval.add_argument('--output')
    surveybench_launch_approval.set_defaults(func=handler)
    surveybench_launch_enforcement = surveybench_sub.add_parser('launch-enforcement-preflight', help='Build launch enforcement/no-drift preflight without launching')
    surveybench_launch_enforcement.add_argument('--approval-packet', required=True)
    surveybench_launch_enforcement.add_argument('--output')
    surveybench_launch_enforcement.set_defaults(func=handler)
    surveybench_next_action = surveybench_sub.add_parser('next-action', help='Emit the next structured SurveyBench replay action from visible task/session/output state')
    surveybench_next_action.add_argument('--task', required=True)
    surveybench_next_action.add_argument('--session')
    surveybench_next_action.add_argument('--actual-dir')
    surveybench_next_action.set_defaults(func=handler)
    surveybench_packet_template = surveybench_sub.add_parser('packet-template', help='Emit schema-only SurveyBench packet skeletons')
    surveybench_packet_template.add_argument('--task', required=True)
    surveybench_packet_template.add_argument('--output-dir')
    surveybench_packet_template.add_argument('--write-files', action='store_true')
    surveybench_packet_template.set_defaults(func=handler)
    surveybench_packet_compose = surveybench_sub.add_parser('packet-compose', help='Compose a visible SurveyBench evidence packet from replay evidence')
    surveybench_packet_compose.add_argument('--task', required=True)
    surveybench_packet_compose.add_argument('--output-dir', required=True)
    surveybench_packet_compose.add_argument('--session')
    surveybench_packet_compose.add_argument('--responses-dir')
    surveybench_packet_compose.add_argument('--write-files', action='store_true')
    surveybench_packet_compose.set_defaults(func=handler)
    surveybench_cluster_hints = surveybench_sub.add_parser('cluster-hints', help='Emit visible replay-derived SurveyBench cluster guidance')
    surveybench_cluster_hints.add_argument('--task', required=True)
    surveybench_cluster_hints.add_argument('--responses-dir')
    surveybench_cluster_hints.set_defaults(func=handler)
    surveybench_ready = surveybench_sub.add_parser('ready-for-prose', help='Check whether visible replay artifacts are ready for survey prose drafting')
    surveybench_ready.add_argument('--task', required=True)
    surveybench_ready.add_argument('--actual-dir', required=True)
    surveybench_ready.add_argument('--session')
    surveybench_ready.set_defaults(func=handler)
    surveybench_launch_record = surveybench_sub.add_parser('launch-record-template', help='Emit a schema-only blinded rerun launch record template')
    surveybench_launch_record.add_argument('--task', required=True)
    surveybench_launch_record.set_defaults(func=handler)
